[functions]
  directory = "api"


[[redirects]]
  from = "/user/login"
  to = "/.netlify/functions/user-login"
  status = 200

[[redirects]]
  from = "/user/register"
  to = "/.netlify/functions/user-register"
  status = 200
