[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
  functions = "lambda" #  netlify-lambda reads this
  publish = "build"

[[redirects]]
  from = "/*"
  to =  "/.netlify/functions/main/*"
  status = 200
