[functions]
  directory = "api"


[[redirects]]
  from = "/user/login"
  to = "/.netlify/functions/user-login"
  status = 200

[[redirects]]
  from = "/user/register"
  to = "/.netlify/functions/user-register"
  status = 200

[[redirects]]
  from = "/time/upload"
  to = "/.netlify/functions/time-upload"
  status = 200

[[redirects]]
  from = "/time/getToday"
  to = "/.netlify/functions/time-get-today"
  status = 200

[[redirects]]
  from = "/time/getWeek"
  to = "/.netlify/functions/time-get-week"
  status = 200
