[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
  functions = "funcions" #  netlify-lambda reads this

[functions]
  directory = "funcions"

[[redirects]]
  from = "/"
  to =  "/.netlify/functions/main"
  status = 200
